<?php

/**
 * @file
 * Contains mailchimp_service.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function mailchimp_service_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the mailchimp_service module.
    case 'help.page.mailchimp_service':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('MailChimp email service integration') . '</p>';
      return $output;

    default:
  }
}
